source "https://rubygems.org"
ruby "3.3.0"

# gems required by cli
gem 'thor'
gem 'terminal-table'

# ==========

# gems required by domain core
# domain core - database adapters
gem "sqlite3"
gem "pg"
gem "mysql2"
