source "https://rubygems.org"
ruby "3.3.0"

# gems required by sinatra
gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'rackup'

# ==========

# gems required by domain core
# domain core - database adapters
gem "sqlite3"
gem "pg"
gem "mysql2"
#domain core - presenter
gem 'terminal-table'
gem 'xml-simple'
